// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbt4gYPNPmXOADsoIXfF01e3hq2cEHLo',
    appId: '1:981258539443:web:d4947742f6152c1d4ffbc6',
    messagingSenderId: '981258539443',
    projectId: 'ai-project-919bc',
    authDomain: 'ai-project-919bc.firebaseapp.com',
    storageBucket: 'ai-project-919bc.firebasestorage.app',
    measurementId: 'G-64VSK0LT49',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANp1C5dgSDW2fRWlNiZBfGeFlXQkD91bU',
    appId: '1:981258539443:ios:788be6844fe7c2c34ffbc6',
    messagingSenderId: '981258539443',
    projectId: 'ai-project-919bc',
    storageBucket: 'ai-project-919bc.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjbt4gYPNPmXOADsoIXfF01e3hq2cEHLo',
    appId: '1:981258539443:web:06edc919d55301ec4ffbc6',
    messagingSenderId: '981258539443',
    projectId: 'ai-project-919bc',
    authDomain: 'ai-project-919bc.firebaseapp.com',
    storageBucket: 'ai-project-919bc.firebasestorage.app',
    measurementId: 'G-NNSCQ9KD17',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANp1C5dgSDW2fRWlNiZBfGeFlXQkD91bU',
    appId: '1:981258539443:ios:788be6844fe7c2c34ffbc6',
    messagingSenderId: '981258539443',
    projectId: 'ai-project-919bc',
    storageBucket: 'ai-project-919bc.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCwZpj2sdCqsGnrrsdzzOAXZr-NuDyHos',
    appId: '1:981258539443:android:6b30b4a6147a7eee4ffbc6',
    messagingSenderId: '981258539443',
    projectId: 'ai-project-919bc',
    storageBucket: 'ai-project-919bc.firebasestorage.app',
  );

}